### ISSUE TITLE
공통 포맷 적용

### ISSUE THREAD

**Issue by phantasmicmeans** [net-lmcd/ManLiHyang-Server#15]
@xowns4817 
Req, Res, Error 등 공통 포맷 적용 부탁드립니다.
적용 후 close 해주세요!!

**Comment by phantasmicmeans** [comment]
@xowns4817

**Comment by phantasmicmeans** [comment]
@xowns4817 @xowns4817 @xowns4817 @xowns4817 @xowns4817

**Comment by xowns4817** [comment]
넵. 알겟습니다 ㅎㅎ
