### ISSUE TITLE
EMAIL 찾기에 따른 본인인증 수단

### ISSUE THREAD

**Issue by phantasmicmeans** [net-lmcd/ManLiHyang-Server#19]
EMAIL 찾기에 따른 본인인증 수단이 필요
- 만리향 정책은 EMAIL 외 개인정보를 보관하지 않기에 식별할 수 있고, 사용자가 구별할 수 있는 무언가 필요

**Comment by doonguk** [comment]
안녕하세요. 백엔드 개발자 @phantasmicmeans 님
프론트개발자 흐드윽 입니다. 새벽이라 머리가 굳었는데 아까 생각난 아이디어를 말해보겠습니다. 

첫째. 휴대폰 본인인증을 추가한다
일반적인 방법으로 휴대폰을 개인정보로 추가하면 유저를 식별 할 수 있지만 디비에 폰 번호를 저장 해야하고, 휴대폰 본인인증할 때 필요한 문자인증은 건수로 돈이 나가는 단점이 있습니다. (인증이 성공된 문자 기준으로 건당 50원)

두번째. 회원가입 때 유저가 자신을 구별할 수 있는 질문을 추가한다.
여기서 질문이란 "내가 졸업한 초등학교 이름은?" 같은 예시를 말합니다.
회원가입 닉네임 + 본인확인 질문을 이용하면 유저를 식별할 수 있지 않을까요?

**Comment by ImIrondroid** [comment]
안녕하세요 
안드로이드 개발자 iron 입니다. 
저희쪽에서 제일 쉽게 접근할 수 있는 아이디어는 고유 닉네임을 사용하는 것 입니다.
고유 닉네임 하나만으로 사용자를 간단하게 식별할 수 있습니다.  하지만 사용자는 원하는 닉네임을 선택할수 없는 가능성이 있는 단점이 있습니다.

궁금한것이 있는데, 사용자들의 데이터는 배열로 저장되는지 궁금합니다. 각 데이터는 인덱스를 가지고 있는지 궁금합니다. 만약 그렇다면, 닉네임 설정을 자유롭게할 수 있고, 사용자의 데이터가 저장된 인덱스만으로도 사용자를 식별할 수 있을 것 입니다.

@phantasmicmeans @doonguk

**Comment by doonguk** [comment]
안녕하세요. 안드로이드 개발자 @Imabubblyiron 님
데이터베이스에서 닉네임과 인덱스를 이용해서 사용자를 식별 한다면 개발자입장 에서는 구별할 수 있지만
사용자입장 에서는 자신의 디비 인덱스를 모르기 때문에 구별하기 힘들지 않을까요?

**Comment by ImIrondroid** [comment]
안녕하세요 프론트 개발자 동욱 @doonguk 님
제가 그거를 답글을 쓴 후에 생각했네요.

**Comment by phantasmicmeans** [comment]
추후 모임때 협의가 필요하겠네요..
@Imabubblyiron @doonguk
