### ISSUE TITLE
게시물 Like 조회 

### ISSUE THREAD

**Issue by doonguk** [net-lmcd/ManLiHyang-Server#30]
좋아요 개수를 확인하기 위해서는
게시물 좋아요 조회 GET /board/{service-code}/like/{board_id} API를 요청 해야 하는데,
Main List 페이지 에서 위와 같이 API를 요청 할 경우 글1개당 API 1번 요청 해야 하니 글 개수가 많이지면
비효율적이지 않을까요??
@xowns4817  @phantasmicmeans

**Comment by phantasmicmeans** [comment]
음 게시물 조회시에 좋아요 정보는 없나요?

**Comment by xowns4817** [comment]
네. 좋아요 테이블 따로 관리하고잇어서 지금은 없습니다... 게시물 테이블에 좋아요 갯수 컬럼 추가하는게 좋을거같네요.

**Comment by doonguk** [comment]
네 알겠습니다!!
